basic:
  device_ids: "1"
  random_seed: 1993
  version_name: "DER_default"
  wandb_dir: "/data/jiantao"
  is_log: True
  save_checkpoint: True
  save_path: "../checkpoint&log"
  method: "DER"
  increment_type: "CIL"
  increment_steps: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]


usual:
  dataset_name: "cifar100"
  data_shuffle: True
  img_size: 32
  backbone: "cifar_resnet32"
  pretrained_path: ""
  drop_rate: 0
  drop_path_rate: 0
  batch_size: 128
  num_workers: 8
  epochs: 170
  optimizer: SGD
  loss_func: CEloss
  scheduler: multi_step
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.0005
  memory_size: 2000
  apply_nme: False
  sampling_method: "herding"

special:
  ft_epochs: 30
  ft_lr: 0.1
  ft_milestones: [15]
  ft_gamma: 0.1
  T: 5


options:
  multi_step:
    milestones: [80, 120, 150]
    gamma: 0.1
  Warm-up-Cosine-Annealing:
    init_ratio: 0.1
    min_lr_ratio: 0.001
