basic:
  random_seed: 1993
  version_name: "Dynamic_ER_imagenet100_b0i10"
  wandb_dir: "/data/jiantao"
  is_log: True
  save_checkpoint: True
  save_path: "../checkpoint&log"
  method: "Dynamic_ER"
  increment_type: "CIL"
#  increment_steps: [ 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]
  increment_steps: [ 10, 10, 10, 10, 10, 10, 10, 10, 10, 10 ]

usual:
  dataset_name: "imagenet100"
  data_shuffle: True
  img_size: 224
  backbone: "timm_resnet18"
  pretrained_path: ""   # /data/jiantao/pretrained_model/resnet18.a1_in1k.safetensors
  drop_rate: 0
  drop_path_rate: 0
  batch_size: 128
  num_workers: 8
  epochs: 150
  optimizer: SGD
  loss_func: CEloss
  scheduler: multi_step
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.0005
  memory_size: 2000
  apply_nme: False
  sampling_method: "herding"

special:
  T: 1
  ft_epochs: 50
  ft_lr: 0.01
  ft_milestones: [15, 30]
  ft_gamma: 0.1

options:
  multi_step:
    milestones: [80, 120]     # [100, 120, 145]
    gamma: 0.1
  Warm-up-Cosine-Annealing:
    init_ratio: 0.1
    min_lr_ratio: 0.001
