basic:
  random_seed: 1993
  version_name: "DA_cifar100_adapter_da_detach"
  is_log: True
  save_checkpoint: False
  save_path: "../checkpoint&log"
  method: "DA"
  increment_type: "CIL"
  increment_steps: [ 10, 10, 10, 10, 10, 10, 10, 10, 10, 10 ]
#  increment_steps: [ 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]

usual:
  dataset_name: "cifar100"
  data_shuffle: True
  img_size: 224
  backbone: "vit_adapter"
  pretrained_path: "/data/jiantao/pretrained_model/vit_base_patch16_224.augreg_in21k_ft_in1k.safetensors"  # /data/jiantao/pretrained_model/vit_base_patch16_224.augreg_in21k_ft_in1k.safetensors
  drop_rate: 0
  drop_path_rate: 0
  batch_size: 64
  num_workers: 8
  epochs: 10
  optimizer: SGD
  loss_func: CEloss
  scheduler: Cosine
  lr: 0.01
  momentum: 0.9
  weight_decay: 0.0005
  memory_size: 0
  apply_nme: False
  sampling_method: ""

special:
  ca_epoch: 5
  ca_lr: 0.01
  num_sampled_pcls: 256
  ca_logit_norm: 0.1
  dm: True

options:
  Cosine:
    eta_min: 0
  multi_step:
    milestones: [8]
    gamma: 0.1
  Warm-up-Cosine-Annealing:
    init_ratio: 0.1
    warm_up_steps: 2
    min_lr_ratio: 0.001
