basic:
  random_seed: 1993
  version_name: "cifar100_b0i10_openclip"
  is_log: True
  save_checkpoint: False
  save_path: "../checkpoint&log"
  method: "PRCLIP"
  increment_type: "CIL"
  increment_steps: [ 10, 10, 10, 10, 10, 10, 10, 10, 10, 10 ]
#  increment_steps: [ 20, 20, 20, 20, 20]
#  increment_steps: [ 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]

usual:
  dataset_name: "cifar100"
  is_openset_test: True
  data_shuffle: True
  img_size: 224
  backbone: "OpenCLIP"
  pretrained_path: "pretrained_model/OpenCLIP_ViT-B-16-DataComp.XL-s13B-b90K"  #  pretrained_model/CLIP_ViT-B-16.pt
  drop_rate: 0
  drop_path_rate: 0
  batch_size: 1
  num_workers: 8
  epochs: 10
  optimizer: SGD
  loss_func: CEloss
  scheduler: Cosine
  lr: 0.1
  momentum: 0
  weight_decay: 0.0002
  memory_size: 2000
  apply_nme: False
  sampling_method: "herding"

special:
  prompt_template: "a photo of a {}."
  ret_ratio: 0.8

options:
  Cosine:
    eta_min: 0
  Warm-up-Cosine-Annealing:
    init_ratio: 0.1
    warm_up_steps: 2
    min_lr_ratio: 0.001
