basic:
  random_seed: 1993
  version_name: "ctf_tuning_icarl_qwert_cifar100_b0i10"
  wandb_dir: "/data/jiantao"
  is_log: True
  save_checkpoint: False
  save_path: "../checkpoint&log"
  method: "CtF_tuning"
  increment_type: "CIL"
  increment_steps: [ 10, 10, 10, 10, 10, 10, 10, 10, 10, 10 ]
#  increment_steps: [ 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]

usual:
  dataset_name: "cifar100"
  data_shuffle: True
  img_size: 32
  backbone: "CLIP"
  pretrained_path: "/data/jiantao/pretrained_model/CLIP_ViT-B-32.pt"
  drop_rate: 0
  drop_path_rate: 0
  batch_size: 64
  num_workers: 8
  epochs: 20
  optimizer: SGD
  loss_func: CEloss
  scheduler: Warm-up-Cosine-Annealing
  lr: 0.1
  momentum: 0.9
  weight_decay: 0
  memory_size: 2000
  apply_nme: True
  sampling_method: "herding"

special:
  coarse_yaml: "/data/jiantao/projects/My_CL_Bank/code/config_yaml/iCarL/icarl_cifar100.yaml"
  use_desc: False
  desc_num: 10
  topk: 5
  lora_r: [0, 0]
  prompt_template: "a bad photo of a {}."


options:
  Cosine:
    eta_min: 0
  Warm-up-Cosine-Annealing:
    init_ratio: 0.1
    warm_up_steps: 2
    min_lr_ratio: 0.001
