basic:
  random_seed: 1993
  version_name: "Ease_imagenet_r_b0i10"
  is_log: True
  save_checkpoint: True
  save_path: "../checkpoint&log"
  method: "Ease"
  increment_type: "CIL"
#  increment_steps: [ 20, 20, 20, 20, 20, 20, 20, 20, 20, 20 ]
  increment_steps: [ 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10 ]

usual:
  dataset_name: "imagenet-r"
  data_shuffle: True
  img_size: 224
  backbone: "vit_adapter"
  pretrained_path: "pretrained_model/vit_base_patch16_224.augreg2_in21k_ft_in1k.safetensors"
  drop_rate: 0
  drop_path_rate: 0
  batch_size: 64
  num_workers: 8
  epochs: 20
  optimizer: SGD
  loss_func: CEloss
  scheduler: Cosine
  lr: 0.05
  momentum: 0.9
  weight_decay: 0.0005
  memory_size: 0
  apply_nme: False
  sampling_method: ""

special:
  use_diagonal: false
  recalc_sim: True
  alpha: 0.1
  beta: 0
  use_init_ptm: false
  use_reweight: True

options:
  Cosine:
    eta_min: 0
