basic:
  random_seed: 1993
  version_name: "WA_imagenet_r_b0i10"
  wandb_dir: "/data/jiantao"
  is_log: True
  save_checkpoint: True
  save_path: "../checkpoint&log"
  method: "WA"
  increment_type: "CIL"
#  increment_steps: [ 20, 20, 20, 20, 20, 20, 20, 20, 20, 20 ]
  increment_steps: [ 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10 ]

usual:
  dataset_name: "imagenet-r"
  data_shuffle: True
  img_size: 224
  backbone: "tv_resnet18"
  pretrained_path: ""
  drop_rate: 0
  drop_path_rate: 0
  batch_size: 64
  num_workers: 8
  epochs: 150
  optimizer: SGD
  loss_func: CEloss
  scheduler: multi_step
  lr: 0.01
  momentum: 0.9
  weight_decay: 0.0005
  memory_size: 2000
  apply_nme: False
  sampling_method: "herding"

special:
  T: 2

options:
  multi_step:
    milestones: [60, 100, 120]
    gamma: 0.1
  Warm-up-Cosine-Annealing:
    init_ratio: 0.1
    min_lr_ratio: 0.001
