basic:
  random_seed: 1993
  version_name: "proof_cifar100_b0i10_v5"
  is_log: True
  save_checkpoint: True
  save_path: "../checkpoint&log"
  method: "Proof"
  increment_type: "CIL"
  increment_steps: [ 10, 10, 10, 10, 10, 10, 10, 10, 10, 10 ]
#  increment_steps: [ 20, 20, 20, 20, 20]
#  increment_steps: [ 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]

usual:
  dataset_name: "cifar100"
  data_shuffle: True
  img_size: 224
  backbone: "CLIP"
  pretrained_path: "pretrained_model/CLIP_ViT-B-16.pt"
  drop_rate: 0
  drop_path_rate: 0
  batch_size: 64
  num_workers: 8
  epochs: 20
  optimizer: AdamW
  loss_func: CEloss
  scheduler: Warm-up-Cosine-Annealing
  lr: 0.001
  momentum: 0.9
  weight_decay: 0.00005
  memory_size: 2000
  apply_nme: False
  sampling_method: "herding"

special:
  prompt_template: "a photo of a {}."
  prompt_length: 3
  attention_heads: 1

options:
  Cosine:
    eta_min: 0
  Warm-up-Cosine-Annealing:
    init_ratio: 0.1
    warm_up_steps: 2
    min_lr_ratio: 0.001
